file:
  dir: C:\Users\qkrgy\Desktop\capstone2\src\main\resources\file\

image:
  dir: C:\Users\qkrgy\Desktop\capstone2\src\main\resources\image\

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://awslearner.ctsq4ue24ukb.ap-southeast-2.rds.amazonaws.com:3306/awslearner?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:h2:tcp://localhost/~/capstone2
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000